### ISSUE TITLE
Add NAND restore function

### ISSUE THREAD

**Issue by zipplet** [GaryOderNichts/recovery_menu#12]
Excellent work on this (and UDPIH)!

It would be really nice to add a NAND backup restore function that can read NAND backup files from the SD card. This would be an easy way to undo damage to the OS, especially when the nature of the damage isn't obvious.

**Comment by GaryOderNichts** [comment]
This is not a planned feature at the moment, due to several reasons.
* UDPIH is still not total brick protection. Restoring a NAND backup (especially SLC) can cause the console to be permanently bricked.
* Even if it's MLC only, tickets are still on the SLC which causes mismatches with installed titles on the MLC.
* People won't investigate the actual issues but just reflash their NAND backups.
  Especially on systems with dying eMMC chips this won't fix any problems and might just cause more harm.

**Comment by zipplet** [comment]
OK, I understand. So the recommended solution would be to install WUPs to replace the bad titles/etc in most cases. Thanks for the clarification.

Another suggestion would be to add a file system browser like GodMode9 on 3DS, unless you think this is covered by another project that can be utilised via recovery menu.
