### ISSUE TITLE
Exploit not working

### ISSUE THREAD

**Issue by Foksse** [GaryOderNichts/recovery_menu#15]
Hello, i saw this recovery menu a few days ago and since i had a second hand bought wii u locked with nnid screen and parental password, i decided to buy a rasp pico and a micro sd, i did everything fine, the pico was flashed and my micro sd works and has the file in it, the pico was plugged in the right place. The problem is that i when i do it perfectly the screen goes black, it doesnt work and the wii u turns off, the gamepad also deconnect, i cant manage to load the recovery menu, i checked every issues but no one was talking about this problem, it might my micro sd since i downloaded the file on an android and android creates android file that isnt removable. Please help me, it seems to come from there but i have no idea, i also started coldboot but nothing, i hope you read this and help me.

**Comment by GaryOderNichts** [comment]
Power off means that the menu can't be read from the SD Card. Make sure to format it as FAT32 and download the file using a PC. Afaik some phones add a file ending to the `recovery_menu` file which won't work.

**Comment by omar16966** [comment]
First thanks for your work. and I have a broken WIIU since 5y I see this fix but when I try using `recovery_menu` file I get nothing on TV but the power LED light is purple and when I use `recovery_menu_dc_init` file I get blue screen with text "There is problem with system Memory...."
- I use UDPIH Nintendo Switch Payload.
- My WIIU GamePad is broken So I can't use it to get the signal 
Thanks.
![IMG20221213165549](https://user-images.githubusercontent.com/53971131/207355598-82d8e5ed-f2f7-4198-9196-e6d7ed75dea9.jpg)
![IMG20221213165907](https://user-images.githubusercontent.com/53971131/207355640-0393b447-7986-452a-ac76-a947692ef79b.jpg)
![IMG20221213165955](https://user-images.githubusercontent.com/53971131/207355665-b63c7f69-6040-4f2e-a90b-a93170df782b.jpg)

**Comment by GaryOderNichts** [comment]
> First thanks for your work. and I have a broken WIIU since 5y I see this fix but when I try using `recovery_menu` file I get nothing on TV but the power LED light is purple and when I use `recovery_menu_dc_init` file I get blue screen with text "There is problem with system Memory...."
> 
>     * I use UDPIH Nintendo Switch Payload.
> 
>     * My WIIU GamePad is broken So I can't use it to get the signal
>       Thanks.

Seems like wrong timing. Try plugging it in sooner / later.

**Comment by GaryOderNichts** [comment]
Original author mentioned that they've fixed the issue.
